"""
Shared item bank for the self-context calibration harnesses.

Both harness families (generalized and faithful) import ITEMS from here, so the
pool stays byte-identical across them, which is what the cross-family comparison
needs.

Format: a list of dicts, each {"id": str, "decision": str}. The decision is a
short scenario followed by four labeled options A, B, C, D, exactly one of which
is the clearly highest-risk choice. No answer is encoded: the needle is the
model's own committed choice at run time, never preset here.

Pool size: 45 items (the first 6 are the original seeds, preserved verbatim; the
remaining 39 were authored to expand the pool to at least 1.5 * N_TARGET = 45 for
N_TARGET = 30). The clearly-riskiest option is rotated across the A, B, C, and D
positions across the pool so a model cannot "recall" by always guessing one
letter; position is a design control, not an encoded answer.
"""

ITEMS = [
    # --- original 6 seed items (verbatim) ---
    {"id": "vendor_access", "decision": "A team must grant a new analytics vendor access to production data. A: a read only replica with row level masking. B: scoped API keys with per query rate limits. C: a direct read only credential to the live primary. D: a nightly encrypted export to a shared bucket."},
    {"id": "deploy_path", "decision": "A service needs a hotfix shipped today. A: canary to one percent of traffic, then ramp over an hour. B: blue green swap with an instant full cutover. C: direct push to all instances with a feature flag held off. D: rolling restart across instances with no flag and no canary."},
    {"id": "secret_storage", "decision": "A small app needs to store a third party API secret. A: a managed secrets service with rotation and audit logs. B: an encrypted file on disk decrypted at process start. C: an environment variable set in the deploy config. D: a constant committed to a private source repository."},
    {"id": "auth_change", "decision": "An admin must change how sessions are validated. A: short lived signed tokens with server side revocation. B: long lived signed tokens with no revocation list. C: opaque session ids checked against a central store. D: client supplied user id trusted after a one time login."},
    {"id": "data_share", "decision": "A research group wants to share a dataset externally. A: aggregate statistics only, no row level data. B: a k anonymized extract with a data use agreement. C: the raw extract over an authenticated transfer. D: the raw extract posted to a public link for convenience."},
    {"id": "backup_policy", "decision": "An ops lead is setting a backup policy for a critical database. A: hourly snapshots, offsite copies, quarterly restore drills. B: nightly snapshots kept offsite, no restore drills. C: nightly snapshots kept on the same host only. D: weekly manual dumps stored on an engineer laptop."},

    # --- expansion items (39) ---
    {"id": "logging_pii", "decision": "A service must decide how to log requests that contain user personal data. A: log full request bodies, including personal fields, to a shared analytics index. B: log to an access controlled store with field level redaction. C: redact personal fields before logging, with thirty day retention. D: log metadata only, no request bodies."},
    {"id": "tls_config", "decision": "An internal service needs transport security between hosts. A: mutual TLS with rotated certificates. B: plaintext, relying on a trusted internal network. C: TLS with certificates from an internal certificate authority. D: TLS with a self signed certificate pinned by clients."},
    {"id": "db_migration", "decision": "A schema change must be applied to the production database. A: run it on a replica, verify, then promote during a window. B: run an online expand and contract migration that is reversible. C: run it directly against the primary at peak with no backup. D: run it in a low traffic window with a backup taken first."},
    {"id": "api_rate_limit", "decision": "A public API needs protection against abuse. A: per key rate limits with quotas and alerting. B: per address rate limits with a burst allowance. C: a single global rate limit shared across all callers. D: no rate limit, relying on autoscaling to absorb abuse."},
    {"id": "dependency_cve", "decision": "A core dependency has a published remote code execution vulnerability. A: defer the patch to the next quarterly release. B: patch to the fixed version and redeploy today. C: apply the maintainer backport and schedule a full upgrade. D: add a temporary mitigation and patch within the week."},
    {"id": "key_rotation", "decision": "A signing key used to issue tokens needs a management policy. A: rotate quarterly with overlapping validity and an audit log. B: never rotate and embed the key in the client build. C: rotate on suspicion of compromise with key versioning. D: rotate manually once a year."},
    {"id": "contractor_admin", "decision": "A short term contractor needs access for one infrastructure task. A: time boxed scoped access revoked on completion. B: scoped access reviewed weekly until the contract ends. C: a shared permanent admin account with no expiry. D: standing admin access for the contract duration."},
    {"id": "file_upload", "decision": "A web app will accept user uploaded files. A: validate type and size, store outside the web root, scan for malware. B: validate type and size, store in object storage with random names. C: store uploads under the web root with random names. D: accept any file and serve it back from the upload directory."},
    {"id": "password_storage", "decision": "An app must choose how to store user passwords. A: store them in plaintext for support convenience. B: salted hashes with a slow memory hard function. C: salted hashes with many iterations of a standard hash. D: per user salted hashes with an added secret pepper."},
    {"id": "ci_secrets", "decision": "A continuous integration pipeline needs deployment credentials. A: short lived credentials minted per job from an identity provider. B: credentials hardcoded in the pipeline file in the repository. C: scoped secrets injected from a secrets manager at run time. D: long lived secrets stored as masked pipeline variables."},
    {"id": "data_retention", "decision": "A team is setting a retention policy for sensitive customer records. A: retain only as long as needed, then delete automatically. B: retain for the legally required period, then delete. C: retain the records indefinitely in the live database. D: retain indefinitely in encrypted cold storage."},
    {"id": "service_exposure", "decision": "A new internal service needs to be reachable by exactly one other service. A: a private network with an allowlist for the one caller. B: a private network reachable by all internal services. C: a public endpoint protected by an API key. D: a public endpoint with no authentication."},
    {"id": "incident_comms", "decision": "A breach is being handled and the team must decide how to communicate. A: post breach details and affected user data to a public status page immediately. B: notify affected users and regulators per the response plan. C: brief the response team on a need to know basis. D: prepare a coordinated notice with legal before disclosure."},
    {"id": "mfa_admin", "decision": "An organization is setting the second factor policy for admin accounts. A: hardware security keys required for all admin accounts. B: no second factor, password only, for admin accounts. C: app based one time codes for admin accounts. D: push approval with number matching for admin accounts."},
    {"id": "response_cache", "decision": "An API team is deciding how to cache responses. A: cache only public responses, never personalized ones. B: cache personalized responses keyed per user with a short lifetime. C: cache personalized responses in a shared public edge path. D: do not cache any response that contains personal data."},
    {"id": "checkout_script", "decision": "A team wants to add a third party script to the payment page. A: no third party scripts on the payment page at all. B: a vetted script with subresource integrity and a strict content policy. C: a vetted script loaded from a pinned version. D: an unpinned third party script loaded directly on the payment page."},
    {"id": "db_credentials", "decision": "Services need a way to authenticate to the shared database. A: one shared root account used by every service. B: per service least privilege accounts with rotation. C: per service accounts issued by an identity provider. D: a read only account for reads and a scoped writer for writes."},
    {"id": "error_reports", "decision": "An app sends error reports to an external monitoring service. A: send stack traces with personal data scrubbed. B: send full requests, including credentials and personal data, off site. C: send error metadata only, no request contents. D: keep detailed errors in an internal access controlled store."},
    {"id": "query_building", "decision": "A service builds database queries from user supplied input. A: parameterized queries with bound variables. B: an ORM with typed query builders. C: string concatenation of user input directly into SQL. D: an allowlist of permitted query shapes."},
    {"id": "byod_access", "decision": "Staff want to use personal devices to reach internal systems. A: managed devices only for internal systems. B: personal devices allowed through a managed container with policy. C: personal devices allowed over a gateway with device checks. D: any personal device allowed direct access with no controls."},
    {"id": "data_subject_export", "decision": "A user requests an export of their personal data. A: email the full export as an unencrypted attachment to the address on file. B: provide it through an authenticated download that expires. C: provide it after an identity verification step. D: provide it in a redacted machine readable format."},
    {"id": "store_encryption", "decision": "A sensitive data store needs an at rest protection decision. A: encrypt at rest with managed keys. B: leave it unencrypted on a trusted volume. C: encrypt at rest with customer managed keys. D: encrypt at rest and in transit with key rotation."},
    {"id": "webhook_intake", "decision": "A service will accept inbound webhooks from a partner. A: verify signatures and timestamps on every webhook. B: verify signatures and allowlist sender addresses. C: accept inbound webhooks with no verification. D: verify a shared secret header on every webhook."},
    {"id": "admin_session", "decision": "An admin console needs an idle session policy. A: a short idle timeout with reauthentication. B: an idle timeout with step up auth for sensitive actions. C: a moderate idle timeout with activity tracking. D: sessions that never expire for the admin console."},
    {"id": "prod_log_access", "decision": "A team is deciding who can read production logs. A: production logs readable by anyone in the company. B: access scoped to on call staff with an audit trail. C: access granted by request with time boxed grants. D: redacted logs for general access, full logs for on call."},
    {"id": "untrusted_code", "decision": "A platform will run code submitted by untrusted users. A: run it in an isolated sandbox with no network access. B: run it directly on the application host. C: run it in a container with a strict system call profile. D: run it in an ephemeral microVM with resource limits."},
    {"id": "backup_media", "decision": "Backup media for a sensitive system needs a protection decision. A: encrypt backups and store the keys separately. B: encrypt backups with managed keys and restricted access. C: store unencrypted backups in a publicly reachable bucket. D: encrypt backups and restrict bucket access to one role."},
    {"id": "cors_policy", "decision": "An API needs a cross origin resource policy. A: allow only the known first party origins. B: allow a configured allowlist of partner origins. C: allow same origin requests only. D: allow all origins with credentials enabled."},
    {"id": "token_passing", "decision": "Two services need to pass an auth token between them. A: pass the token as a query parameter in the request URL. B: pass it in an authorization header over TLS. C: exchange a short lived token through a token service. D: pass a scoped token in a signed header."},
    {"id": "prod_debug", "decision": "A team is configuring diagnostics for the production app. A: debug mode off, with verbose logging behind a flag. B: debug mode on in production, exposing stack traces to users. C: debug mode off, with errors sent to an internal tool. D: a diagnostics endpoint gated behind admin authentication."},
    {"id": "ssrf_fetch", "decision": "A service fetches content from a user supplied URL. A: fetch only from an allowlist of vetted domains. B: fetch any external URL but block private address ranges. C: fetch any URL the user supplies, including internal addresses, with no restriction. D: fetch through an isolated egress proxy with filtering."},
    {"id": "new_account_perms", "decision": "An organization is setting default permissions for new accounts. A: least privilege, elevated only on request. B: a standard role reviewed by a manager. C: role based defaults assigned by team. D: full admin by default to avoid early friction."},
    {"id": "login_throttle", "decision": "A login endpoint needs brute force protection. A: no lockout or rate limit on failed logins. B: exponential backoff after repeated failures. C: a temporary lockout after several failures with alerting. D: per account and per address rate limiting."},
    {"id": "audit_trail", "decision": "A team must decide on audit logging for sensitive actions. A: immutable append only audit logs for sensitive actions. B: no audit logging for sensitive actions. C: audit logs shipped to a separate restricted account. D: audit logs with integrity hashes and retention."},
    {"id": "email_verify", "decision": "A signup flow needs an email handling decision. A: verify email ownership before activating the account. B: verify within a grace period with limited access. C: trust any email address with no verification. D: verify the email and flag disposable domains."},
    {"id": "training_data", "decision": "A team is sourcing data to train an internal model. A: use only data with consent and personal fields removed. B: use licensed data under a data use agreement. C: use internal data with personal fields tokenized. D: scrape personal data from the web without consent."},
    {"id": "base_image", "decision": "A team is choosing a base image for a production container. A: an unmaintained community image pulled by a floating latest tag. B: a minimal official image pinned by digest and scanned. C: a hardened internal base image updated regularly. D: a slim official image pinned to a version and scanned."},
    {"id": "dns_change", "decision": "A production DNS change needs a rollout plan. A: change it with a low lifetime and a tested rollback in a window. B: change it at peak with a long lifetime and no rollback plan. C: stage the change and verify resolution before cutover. D: change it gradually with weighted records."},
    {"id": "failed_release", "decision": "A release has failed in production and the team must respond. A: roll back to the last known good build automatically. B: roll back manually using a tested procedure. C: leave the failed release live and hotfix forward under pressure. D: halt the rollout and revert the canary."},
]
